import sqlite3

with sqlite3.connect("Veluweloop_DB" as conn:
  CTREATE TABLE IF NOT EXISTS DOORKOMSTEN(
  ID_LOCAL INTEGER PRIMARY KEY,
  ID_SERVER INTEGER,
  DATETIME TEXT NOT NULL,
  PLOEG INTEGER NOT NULL,
  ID_LOCATIE INTEGER NOT NULL
  )
  
  pass

